apiVersion: v1
kind: Secret
metadata:
  name: certificate-secret
  namespace: xmemo-system
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    <PEM Certificate as base64 string>
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    <PEM Privatekey as base64 string>
    -----END PRIVATE KEY-----