# Create the Traefik Controller Deployment
# TODO: Scale this up to e.g. 3 Replicas if everything works
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  namespace: xmemo-system
  labels:
    app: traefik
spec:
  replicas: 3
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
          args:
            - --api.insecure
            - --providers.kubernetesingress
            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entrypoint.to=websecure
            - --entrypoints.web.http.redirections.entrypoint.scheme=https
            - --entrypoints.websecure.address=:443
            - --entrypoints.websecure.http.tls
            - --providers.kubernetescrd
            - --providers.kubernetescrd.namespaces=xmemo-system
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: dashboard
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: xmemo-system
  annotations:
    metallb.universe.tf/address-pool: xmemo-pool
spec:
  type: LoadBalancer
  ports:
    - name: web
      targetPort: web
      port: 80
    - name: websecure
      targetPort: websecure
      port: 443
  selector:
    app: traefik
# If you don't use metallb, but a external loadbalancer
# you can simply change the type to NodePort
# add a "nodePort: 3000" port
# and remove the metallb annotation
---
# Create the Traefik Dashboard Service
# TODO: Remove this, it is just here to test the application
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: xmemo-system
  annotations:
    metallb.universe.tf/address-pool: xmemo-pool

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
# If you don't use metallb, but a external loadbalancer
# you can simply change the type to NodePort
# add a "nodePort: 3000" port
# and remove the metallb annotation