apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingress-route
  namespace: xmemo-system
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`xmemo.megakuul.ch`) && PathPrefix(`/api`)
    services:
    - name: api-svc
      port: 80
  tls:
    secretName: certificate-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: xmemo-system
spec:
  selector:
    app: api-pod
  ports:
    - name: web
      port: 80
      targetPort: 80
---
# Create actual Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: xmemo-system
spec:
  selector:
    matchLabels:
      app: api-pod
  replicas: 3
  template:
    metadata:
      namespace: xmemo-system
      labels:
        app: api-pod
    spec:
      containers:
      - name: api-pod
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        image: megakuul/xmemo-api:latest
        ports:
        - name: web
          containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: DB_AUTH_STRING
          value: "mongodb+srv://xmemo-api:password@cluster-hostname/?retryWrites=true&w=majority"
        - name: JWT_SECRET_KEY
          value: "yourjwtsecret"
        - name: PARTIAL_UPDATE_MODE
          value: "false"
# The API URL is defined directly in the docker-image, this is because the vite-environment variables need to be initialized during build process
# The API URL points to https://xmemo.megakuul.ch/api