# Create Traefik Loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: xmemo-system
  annotations:
    metallb.universe.tf/address-pool: xmemo-pool
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 80
    - protocol: TCP
      port: 443
      name: websecure
      targetPort: 443
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-router
  namespace: xmemo-system
spec:
  rules:
  - host: "test.megakuul.ch"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx 
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: xmemo-system
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# Create actual Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: xmemo-system
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      namespace: xmemo-system
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        image: nginx:1.14.2
        ports:
        - containerPort: 80