apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ip
  namespace: metallb-system
spec:
  ipAddressPools:
  - xmemo-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: xmemo-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.1.1.60/32