name: Build and Push Docker Image for the API and the APP

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    if: "!contains(github.event.head_commit.message, '--no-push')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract API version
        id: get_api_version
        run: |
          cd api
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Extract APP version
        id: get_app_version
        run: |
          cd app
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Build and push API
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: megakuul/xmemo-api:latest , megakuul/xmemo-api:${{ steps.get_api_version.outputs.version }}
  
      - name: Build and push APP
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: megakuul/xmemo-app:latest , megakuul/xmemo-app:${{ steps.get_app_version.outputs.version }}

