name: Build and Push Docker Image for the API and the APP

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image for API
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd api
          API_VERSION=$(jq -r .version package.json)
          docker buildx build --platform linux/amd64 -t megakuul/xmemo-api:${API_VERSION} -t megakuul/xmemo-api:latest --push .

      - name: Build and push Docker image for Frontend
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd app
          FRONTEND_VERSION=$(jq -r .version package.json)
          docker buildx build --platform linux/amd64 -t megakuul/xmemo-app:${FRONTEND_VERSION} -t megakuul/xmemo-app:latest --push .

