apiVersion: v1
kind: Secret
metadata:
  name: certificate-secret
  namespace: xmemo-system
type: Opaque
data:
  tls.crt: <PEM Certificate as Base64String>
  tls.key: <PEM Private Key as Base64String>
