kind: PersistentVolume
apiVersion: v1
metadata:
  name: ssl-certs
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ssl-certs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: xmemo-system
  name: ssl-certs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi