# Create the Traefik Controller Deployment
# TODO: Scale this up to e.g. 3 Replicas if everything works
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  namespace: xmemo-system
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v2.10
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          args:
            - --api.insecure
            - --providers.kubernetesingress
          ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080
---
# Create the Traefik Dashboard Service
# TODO: Remove this, it is just here to test the application
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: xmemo-system
  annotations:
    metallb.universe.tf/address-pool: xmemo-pool

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
# Create the Traefik Service to expose the Controller (the controller will then redirect it to the defined Ingress Route)
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: xmemo-system
  annotations:
    metallb.universe.tf/address-pool: xmemo-pool
spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      port: 80
  selector:
    app: traefik