apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: xmemo-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: xmemo-system
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
      - name: traefik-ingress-lb
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        image: traefik:v2.4.8
        args:
        - --api.insecure
        - --providers.kubernetesingress
        - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
        - --certificatesresolvers.cloudflare.acme.email=megakuul@gmx.ch
        - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
        - --certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme-cloudflare.json
        ports:
        - name: web
          containerPort: 80
        - name: websecure
          containerPort: 443
        env:
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              key: email
              name: cloudflare-credentials
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              key: apiKey
              name: cloudflare-credentials
        volumeMounts:
        - name: ssl-certs
          mountPath: /ssl-certs
      initContainers:
      - name: volume-permissions
        image: busybox:1.31.1
        command: ["sh", "-c", "mkdir -p /ssl-certs && chmod -Rv 600 /ssl-certs/*"]
        volumeMounts:
          - name: ssl-certs
            mountPath: /ssl-certs
      volumes:
      - name: ssl-certs
        persistentVolumeClaim:
          claimName: ssl-certs
